networks:
  eclipse-mosquitto:
    driver: bridge
    name: eclipse-mosquitto
services:  
  eclipse-mosquitto:
    image: eclipse-mosquitto:2.0.14
#    image: eclipse-mosquitto-new:latest
    container_name: eclipse-mosquitto
    volumes:
#      - ./config/mosquitto-no-auth.conf:/mosquitto/config/mosquitto.conf
      - ./config/mosquitto-mtls-auth.conf:/mosquitto/config/mosquitto.conf
      - ./certs/ca.crt:/mosquitto/data/ca.crt
      - ./certs/192.168.1.204.pem:/mosquitto/data/localhost.pem
      - ./certs/192.168.1.204.key:/mosquitto/data/localhost.key
      - data:/mosquitto/data
      - log:/mosquitto/log
    ports:
#      - 1883:1883
      - 8883:8883
#      - 9001:9001
    restart: unless-stopped
    networks:
      - eclipse-mosquitto
volumes:
  data:
    name: data
  log:
    name: log
